### ISSUE TITLE
Is there a valid use case for teams discussions?

### ISSUE THREAD

**Issue by tobie** [ampproject/meta#25]
Team discussions aren't public; you need to be an member of the org to have access to them. As such they shouldn't be used for most conversations.

This should be stated somewhere, along with the preferred means of communicating with each WG (probably issues / slack).

**Comment by mrjoro** [comment]
I think we've decided not to use the GitHub teams for discussion.  We use them as a roster for granting permissions when needed, and will soon publish the roster publicly on amp.dev since they aren't public.

I'm not sure people have checking the GitHub team discussions in their workflow.

**Comment by mrjoro** [comment]
And for the second part, I think each WG now documents in their [wg-* repo README.md files](https://github.com/ampproject?utf8=%E2%9C%93&q=wg-&type=&language=) the best way to communicate with them, and the [AC[(https://github.com/ampproject/meta-ac/blob/master/WORKING_MODE.md)/[TSC](https://github.com/ampproject/meta-tsc/blob/master/WORKING_MODE.md) have both documented work modes.

I'll go ahead and close this issue for now.
