### ISSUE TITLE
CLA required?

### ISSUE THREAD

**Issue by mnot** [ampproject/meta#3]
It would be good to clarify whether members of the AC, TSC, etc. would need to accept the CLA. I'm assuming they would, but that needs to be explicit (here and on the Google form).

**Comment by tobie** [comment]
That's a good point.

It's implicit for the TSC, are it's "composed of members with significant experience contributing to AMP," but should nonetheless be called out explicitly.

For the AC, I think the requirements are (1) to be able to publish the AC's output under a CC-BY license or similar and, (2) to avoid making patent-encumbered suggestions to the project or to standard bodies. If the CLA covers both of these cases, than asking AC members to accept it seems to be the best solution.

**Comment by mrjoro** [comment]
@cramforce should we make this more explicit in the proposal?

**Comment by cramforce** [comment]
Maybe something like.

Code contributions require the acceptance of the project's CLA. At this time, code contributions require consent to Google's CLA.

**Comment by tobie** [comment]
The risk for the AC is really only limited patents, as any code contribution would have to go through the regular contribution path and require a CLA to be signed.

If patents are a concern, the easiest path forward is to ask all AC members to sign Google's CLA. We can always revisit this once the project is moved to a foundation.

If patents aren't a concern and only copyright is a concern, then the CLA is already required to contribute code, so we don't need to add a specific comment to the governance document.

**Comment by cramforce** [comment]
I don't really see the need to extend CLA coverage beyond what we have. It covers the unit of distribution.

One note: We have a dedicated repo for publishing design documents to get them covered under the CLA. We only use this if the doc doesn't easily fit into GH issue markdown. https://github.com/ampproject/design-docs

**Comment by mnot** [comment]
This approach seems to be biased towards the folks who are leadership being code contributors. If the project is just producing software, that seems somewhat reasonable, but if you're trying to produce specifications and get buy-in from many parts of the industry, not so much.

**Comment by cramforce** [comment]
@mnot Are you arguing we should extend a CLA requirement for more types of contributions? We'd definitely rather aim in the opposite direction and remove red tape where possible.

**Comment by tobie** [comment]
I believe @mnot’s concern is around IP protection for specifications. A CLA protects the specification and allows it to be provided royalty free (like other W3C, WHATWG, and Ecma specifications). Sure, it’s a bit of extra red tape, but it’s one of the important elements of keeping the web open.

I must admit that I haven’t put enough thought on the AMP spec itself. Other web-related specs that would originate from AMP should clearly be funelled to WICG or WHATWG, but I’m not east the path forward is for the AMP spec itself. We should definitely talk about this more.

**Comment by cramforce** [comment]
I should also clarify: All contributions that land in a repository are covered by CLA. This does include docs, specs, etc.

For most web standards I'd imagine that the actual specs would live outside of the ampproject GitHub org (the scope of our CLA) such as in WICG repos.

**Comment by tobie** [comment]
Alright so concretely, would you both be OK with adding the following to the governance document., either split-up between the TSC and AC sections or in a section of its own:

> New TSC members which haven't already signed the CLA as part of their prior contributions are required to do so upon joining the TSC.
> 
> AC members aren't formally required to sign the CLA, but will be required to do so should they decide to contribute to code, documentation, specifications, design documents, or in any other way where securing IP commitment would be important to keep the projet open source and royalty free.

**Comment by cramforce** [comment]
SGTM

**Comment by mnot** [comment]
That works.
