### ISSUE TITLE
Provide a mechanism for Working Group updates to the TSC, AC and community

### ISSUE THREAD

**Issue by mrjoro** [ampproject/meta#31]
The TSC has requested a mechanism whereby the Working Groups can provide quarterly updates to the TSC, AC and community.  Although most WGs provide [bi-weekly status updates](https://github.com/search?q=org%3Aampproject+label%3A%22Type%3A+Status+Update%22&unscoped_q=label%3A%22Type%3A+Status+Update%22), these quarterly updates will provide an opportunity to summarize higher-level accomplishments and goals over a longer period of time.

I propose:

- At each weekly design review 15 minutes will be alloted for a WG to present an update and field questions from the TSC/AC/community.  The WG facilitator or their designate will present the update.
- The WG update will summarize the work of the WG for the prior 3 months and detail the WG's priorities for the next 3 months and beyond.
- The WG presenting for a given week will share this update in a GitHub issue at least 24 hours before presenting the update at the design review.  This will allow the global community to review the update and add questions/comments.
- We will rotate through the WGs so that each WG will present approximately quarterly.  (There are currently [13 WGs](https://github.com/ampproject?utf8=%E2%9C%93&q=wg-&type=&language=).)

/cc @ampproject/tsc @ampproject/ac

**Comment by cramforce** [comment]
I think this sounds good. A couple comments:

- I find prereview not necessary for this case.
- It'd be nice if we had a well defined way to subscribe to these updates

**Comment by nainar** [comment]
Do we need a quarterly update from the CoC WG? The TSC approved the idea of a transparency report [here](https://github.com/ampproject/meta-tsc/issues/4#issuecomment-455262479). This fits in well with that discussion.

**Comment by andrewwatterson** [comment]
One downside to this approach is that folks have to tune in every week to keep rolling context on the project. I understand the appeal of spreading out the updates over time, but one Design Review dedicated to an update from all the teams per quarter would allow interested parties to get a bunch of distilled updates with less of a time committment.

**Comment by davidstrauss** [comment]
While we've been actually having the vast majority of scheduled TSC meetings, I recall the original plan was to have them scheduled a bit more frequently than necessary so that cancelling/skipping ones here or there wouldn't be an issue.

If we have a rotating schedule of AC/WG presentations, then cancelling a TSC meeting would either disruptively shift the AC/WG update schedule or create a six-month delay between updates (which seems too long). Of course, we could rebook any cancelled TSC meeting, but the intent of the slightly over-frequent cadence was to avoid that necessity.

**Comment by cramforce** [comment]
My understanding is that these presentations aren't at the TSC meeting, but rather part of the weekly design review series.

**Comment by cramforce** [comment]
Please specify how these are going to be scheduled. Assuming it is a fixed round-robin scheme.

Otherwise, this is approved by the TSC

**Comment by mrjoro** [comment]
Let's go with a fixed round-robin scheme.  I'll create a schedule and start adding them to the design reviews next week.

@andrewwatterson regarding the idea of having all of the updates once a quarter, I do see some benefits to that approach but spreading them out has some advantages as well--e.g. focused attention on a WG and the ability to dive a little bit deeper.  We can try this approach and see how it goes.

@cramforce did the TSC have any feedback on @nainar's question about whether the Code of Conduct WG should present these updates?

**Comment by cramforce** [comment]
We didn't discuss the CoC group. I'd say: That is up to the group. It may be more appropriate to present directly to the TSC.

**Comment by mrjoro** [comment]
Initial schedule is now posted in #33, with the first update scheduled for next week.

**Comment by nainar** [comment]
Sorry I missed @cramforce's answer to my question. We can do an annual update to the TSC to coincide with the annual transparency report.
