### ISSUE TITLE
Define (optional) baseline expectations for Working Group membership

### ISSUE THREAD

**Issue by mrjoro** [ampproject/meta#36]
AMP's [governance model provides](https://github.com/ampproject/meta/blob/master/GOVERNANCE.md#working-groups) for the TSC to create Working Groups (WGs) and set their initial membership, and then for the WG to adjust its own membership using the [consensus-based decision making process](https://github.com/ampproject/meta/blob/master/GOVERNANCE.md#decision-making-policy).

Although each WG is free to define for itself how members are added/removed, I have heard from several people in the community that it can be handy to have a baseline understanding of what is expected of WG members that WGs may choose to adopt.

We can use this issue for discussion on this topic, and then I'll update the [WG best-practices doc](https://github.com/ampproject/meta/blob/master/working-groups/best-practices.md).

As a starting point, here's how I think about WG membership:

- Members of a Working Group are expected to be contributing in a significant way to the work of the Working Group.  Significant code contributions is one way to demonstrate this, but you can also demonstrate this through things like driving an overarching product vision for the WG.
- Working Group members should be actively participating in WG discussions and generally aware of/involved in the work of the WG beyond their own projects.
- You don't have to be a member of a Working Group to participate in discussions, propose ideas, have feedback on issues/PRs/etc.

/cc @ampproject/tsc

**Comment by torch2424** [comment]
cc @curseagain Currently working on our process, feel free to follow this 😄
