### ISSUE TITLE
Document a process for creating new ampproject repositories

### ISSUE THREAD

**Issue by mrjoro** [ampproject/meta#41]
We should have a documented process for approving new ampproject GitHub repos.

One proposal is similar to the I2I process--just require 3 members of @ampproject/wg-approvers to approve.

Ideally we'd include some guidelines for what makes a good ampproject repo as well.

/cc @ampproject/tsc @rcebulko @kristoferbaxter @tobie

**Comment by rcebulko** [comment]
It might be worth setting expectations for ie. if I create a repo under `ampproject`, I should be expected to maintain it or define a working group to own it (or something along those lines)

**Comment by davidstrauss** [comment]
> I should be expected to maintain it or define a working group to own it (or something along those lines)

Perhaps new repos could include an `OWNERS.yaml`, even if we don't run the related bots on the additional repos. The aforementioned format supports both individuals and working group owners. Proposals for new repos could include the expected `OWNERS.yaml` to be added on approval.

I'm also +1 on having three members of @ampproject/wg-approvers as the gate-keeping.

**Comment by rcebulko** [comment]
If needed, for repos that grow large enough/have enough contributors for it to be relevant, the owners bot can be deployed for any repo.

**Comment by tobie** [comment]
We should make a distinction between repositories for projects and working groups.

**Comment by rudygalfi** [comment]
Just looking over old issues: what's the status of this one?

**Comment by mrjoro** [comment]
We never reached a conclusion on this as far as I can tell.  Shall we just go with the "create a new repo after 3 approvers approve it"?

**Comment by dvoytenko** [comment]
Seems like the bar should be a bit higher than just 3 approvers.

**Comment by cramforce** [comment]
Dima: Could you explain your reasoning a bit more?

I both kind of share in intuition and don't want to make it too complicated.

**Comment by dvoytenko** [comment]
I think so far wg-approvers was constructed mainly to support technical operations, such as cherrypicks. This seems more of an ownership function. I'd think at least a clear FYI would need to be given to TSC? Not sure if a full approval from TSC is needed though.

**Comment by cramforce** [comment]
Yeah. The main issue is that the TSC only meets every 2 weeks. So if we put them in the critical path the worst case would be much worth than our legacy process that folks didn't like.

**Comment by rcebulko** [comment]
Perhaps 3 approvers including at least one TSC member, who could then take up the mantle of reporting to TSC at their next meeting?

**Comment by cramforce** [comment]
Decision from the TSC: 3 approvers from @ampproject/wg-approvers  and FYI to @ampproject/tsc

**Comment by rudygalfi** [comment]
I proposed adding a step to create an issue in http://github.com/ampproject/meta that mentions the TSC group, serving as an FYI.

**Comment by rudygalfi** [comment]
Closing this because I think it was covered by https://github.com/ampproject/meta/pull/64
