### ISSUE TITLE
Clean up ampproject GitHub teams

### ISSUE THREAD

**Issue by mrjoro** [ampproject/meta#43]
We currently have 44 GitHub teams in the ampproject org.  Many of these are old, and it's not clear most teams other than the governace ones (wg-*, AC, TSC, Collaborators/Reviewers/Approvers) are used for much.

We primarily use teams for:
-  giving permissions to (e.g. Reviewers have write access to amphtml, teams can be referenced in OWNERS files)
- @-mentioning a list of people on an issue/PR
- assigning a group as a reviewer (but this only works for teams with write access to the repo, so it's very limited)

Teams have some problems:
- they're only visible to members of the ampproject org (though for the governance teams we're going to [start showing them on amp.dev](https://github.com/ampproject/amp.dev/issues/1699))
- there are now some duplicate teams that can make it unclear who to talk to (e.g. Ads vs. wg-ads vs. A4A?)
- we have some company-based teams that are almost definitely out of date (e.g. the Google team doesn't have everyone who works at Google)
- we don't really use many of the features of teams, e.g. the discussion mechanism (which also have [some problems](https://github.com/ampproject/meta/issues/25))

**My proposal:**
- Keep all of the governance teams, which I believe includes all of the teams that we are using for permissions.
- Delete all other teams that aren't commonly referenced on issues.

There are some teams we'd remove:

- @ampproject/a4a  -> this is the non-wg group that has been mentioned in issues/prs the most by far; is this distinct from wg-ads? (if it is, we can keep it but should make it clear what the difference is)
- @ampproject/adobe, @ampproject/automattic, @ampproject/chartbeat, @ampproject/google, @ampproject/jw-player, @ampproject/microsoft, @ampproject/nuzzel, @ampproject/parsely, @ampproject/pinterest, @ampproject/rebelmouse, @ampproject/twitter 
- @ampproject/ads -> we'll delete this in favor of wg-ads
- @ampproject/alp -> Ads Landing Pages?  replace with wg-ads
- @ampproject/amp-viewer-master-mergers -> all members are already listed individually on viewer repo
- @ampproject/contributors -> it's not clear what this was for
- @ampproject/docs -> replace with wg-outreach
- @ampproject/publishers -> it's not clear what this team is used for
- @ampproject/runtime -> replace with wg-runtime
- @ampproject/validator -> replace with wg-caching (the Validator and Caching WG)

Teams I'm not sure about:
- @ampproject/cloudflare -> this has been referenced on 15 issues/PRs; should we keep it?  Or should the relevant people be on wg-caching?
- @ampproject/security -> perhaps we should have a Security WG?
- @ampproject/video-on-amp -> should this just be wg-ui-and-a11y?

Teams we'd keep:
- AC
- Bots-amphtml
- Cherry-Pick-Approvers
- Collaborators-amphtml
- Reviewers-amphtml
- TSC
- wg-access-subscriptions
- wg-ads
- wg-amp4email
- wg-analytics
- wg-approvers
- wg-caching
- wg-codeofconduct
- wg-infra
- wg-outreach
- wg-performance
- wg-runtime
- wg-stories
- wg-ui-and-a11y
- wg-viewers
- working-groups (parent team for all of the wg-* teams)

_For reference, here is the current list of GitHub teams and the number of times each team has been mentioned on an ampproject issue or PR:_

A4A (144)
AC (10)
Adobe (0)
Ads (18)
ALP (0)
amp-viewer-master-mergers (0)
Automattic (0)
Bots-amphtml (0)
Chartbeat (0)
Cherry-Pick-Approvers (29)
Cloudflare (15)
Collaborators-amphtml (0)
Contributors (0)
Docs (1)
Google (0)
JW-Player (0)
Microsoft (0)
Nuzzel (0)
Parsely (0)
Pinterest (0)
Publishers (0)
RebelMouse (0)
Reviewers-amphtml (1)
runtime (4)
Security (0)
TSC (39)
Twitter (0)
validator (6)
Video-on-AMP (2)
wg-access-subscriptions (16)
wg-ads (64)
wg-amp4email (12)
wg-analytics (31)
wg-approvers (54)
wg-caching (46)
wg-codeofconduct (2)
wg-infra (49)
wg-outreach (27)
wg-performance (13)
wg-runtime (20)
wg-stories (22)
wg-ui-and-a11y (73)
wg-viewers (4)
working-groups (0)

**Comment by jridgewell** [comment]
Deleting `@ampproject/runtime` SGTM.

**Comment by cramforce** [comment]
Sounds very reasonable to me!

CC @ampproject/tsc

**Comment by alanorozco** [comment]
+1 to `@ampproject/video-on-amp` to be `wg-ui-and-a11y`.

**Comment by jpettitt** [comment]
A security & privacy wg sounds like a good idea

**Comment by Gregable** [comment]
@dknecht for recommendations on the @ampproject/cloudflare team.

**Comment by honeybadgerdontcare** [comment]
+1 to `@ampproject/validator -> replace with wg-caching (the Validator and Caching WG)`

**Comment by lannka** [comment]
@keithwrightbos @jeffkaufman as we're removing the `@ampproject/a4a`, do you want to migrate to @ampproject/wg-ads ?

**Comment by jeffkaufman** [comment]
That seems fine; do we need to do anything?

**Comment by lannka** [comment]
> That seems fine; do we need to do anything?

@jeffkaufman just keep contributing to AMP :-) also be prepared to be pinged by any messages that sent to `@ampproject/wg-ads`. also, please join our [Slack channel](https://github.com/ampproject/wg-ads#communication-channels) for any discussion.

**Comment by jeffjose** [comment]
a4a -> wg-ads SGTM.

**Comment by msukmanowsky** [comment]
Would it be helpful to keep an analytics working group which consolidates: @ampproject/adobe,  @ampproject/chartbeat, @ampproject/parsely?

**Comment by mrjoro** [comment]
@msukmanowsky we have the @ampproject/wg-analytics Working Group team; we could add people who are actively working on analytics to that WG.  /cc @zhouyx who is the analytics WG facilitator.

**Comment by leonampd** [comment]
Hello everyone I was added to `publishers` team some years ago when the project was in the "closed beta" for some players. Maybe there's no one working on this, I guess. I'm not.

**Comment by gibrown** [comment]
Removing @ampproject/automattic seems fine. Most of the WordPress AMP plugin work is being handled by others at this point and I think other groups would make more sense to engage through anyways. Cheers.

**Comment by mrjoro** [comment]
Thanks everyone for the comments!  I'll go ahead and make these changes now.

I'll also follow up on the security & privacy WG question separately.

**Comment by mrjoro** [comment]
I've now made all of these changes.  If you notice any weird behavior, please let me know.

I ended up deleting amp-viewer-master-mergers since the 3 members of that team already had write permissions individually on the viewer repo, and we don't currently have teams for most of the smaller repos.
