### ISSUE TITLE
Create project charter

### ISSUE THREAD

**Issue by tobie** [ampproject/meta#45]
The OpenJS Foundation requires projects have a project charter.

The purpose of a project charter is to provide a brief introduction to the project from a technical, community, or business perspective. The document also connects a project's community leadership and governance with the OpenJS Foundation's governance. 

Here's a [template](https://github.com/openjs-foundation/cross-project-council/blob/master/PROJECT_CHARTER_TEMPLATE.md) for it.

**Comment by mrjoro** [comment]
Doc will live in meta repo and be mirrored on amp.dev.

/cc @ampproject/wg-outreach

**Comment by mrjoro** [comment]
See https://github.com/openjs-foundation/cross-project-council/pull/405

**Comment by tobie** [comment]
Started a document [here](https://docs.google.com/document/d/1jH7olg_nmPsAEj3kFJdQV3yfVX9p4wb2NZ9OZJvE9Mc/edit).

**Comment by tobie** [comment]
During the Foundation Onboarding WG's call today, we discussed the existing indirections in the Charter (which points to outside documents such as GOVERNANCE.md or the vision/mission statement), and @jorydotcom and @brianwarner weren't expecting this to be a concern.

**Comment by tobie** [comment]
We can get this charter approved by the CPC as soon as it is ready.

**Comment by tobie** [comment]
An issue was opened with the Foundation's CPC last week (https://github.com/openjs-foundation/cross-project-council/issues/552). It was discussed in the CPC meeting today and should automatically get approved by next week if there are no oppositions.
