### ISSUE TITLE
Open source `storybook-addon-amp`

### ISSUE THREAD

**Issue by wassgha** [ampproject/meta#57]
![image](https://user-images.githubusercontent.com/591655/82369470-ee153700-99cb-11ea-848a-94ebae2fdd08.jpeg)

Request to spin off the storybook AMP addon (currently living under `build-system/tasks/storybook/amp-env`) as a standalone repository (`ampproject/storybook-addon-amp`) and publish it on `npm` as `storybook-addon-amp`.

This allows:
- AMP can now simply `import { withAmp } from "storybook-addon-amp"` instead of using a long relative path to the addon
- Separate storybook dependencies from the addon's specific dependencies inside the `amphtml` repository
- Provide outside projects with a way to render AMP components inside storybook
- Provide a natural place for documentation of the usage of the addon

**Comment by wassgha** [comment]
@ampproject/tsc @ampproject/wg-ui-and-a11y

**Comment by cramforce** [comment]
Good idea

**Comment by wassgha** [comment]
Can someone guide us though the aproval process and creating a repository under `ampproject/`

**Comment by cramforce** [comment]
+ @mrjoro 

So, far this is still the google launch process for OSS projects (pending switch over to the foundation)

**Comment by dvoytenko** [comment]
Since the switch to the foundation is over, let's approve this here. 

Approved from me. Still need 2 more approvers from @ampproject/wg-approvers

**Comment by cramforce** [comment]
LGTM2

**Comment by rsimha** [comment]
LGTM3. Glad to see this grow into a standalone piece of infrastructure.

**Comment by mrjoro** [comment]
Great!  I've created https://github.com/ampproject/storybook-addon-amp and made @wassgha , @dvoytenko and @kristoferbaxter admins. :)

**Comment by kristoferbaxter** [comment]
Closing since this has been resolved.
