### ISSUE TITLE
Create a new ampproject repo for the Java AMP Validator

### ISSUE THREAD

**Issue by Gregable** [ampproject/meta#58]
I'd like to request @ampproject/wg-approvers approval for creating a new ampproject repo: `ampproject/validator-java`.

**Background**

The AMP Validator is currently available inside `ampproject/amphtml` as a Javascript implementation [here](https://github.com/ampproject/amphtml/tree/master/validator).

Recently we've added a new fork of the [validator in Java](https://github.com/ampproject/amphtml/tree/master/validator) at the same location to support specific use cases of the @ampproject/wg-amp4email Working Group. However, due to development realities, the @ampproject/wg-caching  and @ampproject/wg-infra groups decided that we'd like to allow the Java validator to be a "fast follow" fork which can fall out of sync for short periods of time. This decision invalidates the original motivation for putting the Java Validator in the same repo as the main validator codebase. Splitting the code into it's own repo will simplify many of the build and release automation for both the Java Validator and AMP HTML.

**Comment by rcebulko** [comment]
Related: https://github.com/ampproject/amphtml/issues/28533#issuecomment-631630774

**Comment by cramforce** [comment]
LGTM1 as member of @ampproject/wg-approvers

**Comment by dvoytenko** [comment]
LGTM2 as member of @ampproject/wg-approvers

**Comment by rsimha** [comment]
LGTM3 as member of @ampproject/wg-approvers

**Comment by Gregable** [comment]
Closing as approved with 3 approvals.
