### ISSUE TITLE
Remove Google Admin and googlebot as owners of ampproject

### ISSUE THREAD

**Issue by mrjoro** [ampproject/meta#61]
Google Admin and googlebot currently have Owner permissions for ampproject, as shown at https://github.com/orgs/ampproject/people?query=google

We should remove these permissions after we have established that any necessary OpenJSF equivalents are in place.  (For example, we cannot remove googlebot until the new CLA is in place as described in #60.)

/cc @ampproject/wg-foundation-onboarding @tobie @jorydotcom @brianwarner @rsimha @ampproject/wg-infra

**Comment by tobie** [comment]
@mrjoro can you confirm this can be closed?

**Comment by rsimha** [comment]
I can confirm that the google accounts are no longer contributors / owners of ampproject, and that we have fully moved to the OpenJSF CLA. This issue can be closed.
