### ISSUE TITLE
Determine whether we can add shared drive support for amp.dev G Suite

### ISSUE THREAD

**Issue by mrjoro** [ampproject/meta#62]
We currently have [G Suite Basic](https://support.google.com/a/answer/6047848) for amp.dev (to provide email, Drive, etc.).

G Suite Basic does not support shared drives, which is a desirable feature (e.g. for more easily sharing collaborative docs).

Shared drive support is available with [G Suite for Nonprofits](https://support.google.com/nonprofits/answer/3367223?hl=en).  The [eligibility requirements for G Suite for Nonprofits](https://support.google.com/nonprofits/answer/3215869) requires that the organization be registered as a charitable organization.

- Are OpenJSF or Linux Foundation considered "charitable organizations" in the US?
- Does OpenJS or Linux Foundation have some other arrangement with Google that would allow us to upgrade the amp.dev G Suite plan to get shared drive support without additional cost?  (My sense is that the feature is a "nice to have" feature that would not necessarily justify extra cost.)

@brianwarner can you help us with answers to these?

/cc @dvoytenko who brought up the issue

**Comment by tobie** [comment]
I somehow missed this.

OpenJSF is a 501(c)(6) so not eligible under [Google's terms](https://support.google.com/nonprofits/answer/3215869) which state 501(c)(3) status is required.
