### ISSUE TITLE
Create repository for Official AMP Plugin for WordPress site

### ISSUE THREAD

**Issue by amedina** [ampproject/meta#63]
Repository name: `amp-wp.org`

Repository content: theme for Official AMP Plugin site: https://wordpress.org/plugins/amp/

Notes: this repository will contain all the code fir the AMP plugin site, and it will also be used for the blog section of `amp.dev`

**Comment by nainar** [comment]
cc @mrjoro

**Comment by mrjoro** [comment]
Sounds good to me!

It looks like the process for approving new repos was never actually finalized (#41).

In the absence of a formal approved process, let's go with an informal one for now and notify the @ampproject/tsc while getting 3 members of @ampproject/wg-approvers to approve.

Can we get a +1 from 3 members of wg-approvers?

**Comment by Gregable** [comment]
+1

**Comment by amedina** [comment]
cc @dvoytenko

**Comment by dvoytenko** [comment]
+1

**Comment by cramforce** [comment]
+1

**Comment by mrjoro** [comment]
I have created https://github.com/ampproject/amp-wp.org and made @amedina an admin.
