### ISSUE TITLE
Refactor Subset of AMP Working Groups

### ISSUE THREAD

**Issue by kristoferbaxter** [ampproject/meta#65]
Over 2020, members of the AMP Project have focused on improving overall performance and increasing the usefulness of AMP Extensions both inside and out of AMP Documents.

With these efforts it's become increasingly clear that dedicated Working Groups require more clear definitions of the swimlanes they operate in.

To this end, @rsimha (facilitator of @ampproject/wg-infra), @lannka (facilitator of @ampproject/wg-ads), @zhouyx (facilitator of @ampproject/wg-analytics), @nainar (facilitator of @ampproject/wg-ui-and-a11y), and myself (facilitator of @ampproject/wg-performance) have been discussing a refactor of the existing Working Groups to better organize around these important issues.

| Group | Performance  | Monetization | Infrastructure | Bento | Components
|:------------- | ------------- | ------------ | ------------- | ------------ | -------------
| WG Facilitator | Erwin Mombay | Hongfei Ding | Raghu Simha | Dima Voytenko | Yuxuan Zhou
| Responsibilities | Load and Runtime performance of AMP and its various formats, including Web Stories. | All forms of monetization with a large number of partners. | Build and deploy AMP artifacts, improving release quality incrementally. | Convert existing extensions for usage outside AMP Documents. | Determine when AMP extensions are additive for ecosystem while preserving analytics and tracking features. 
| Changes | Merging of the previous `performance` and `runtime` working groups. | Extend focus to other monetization approaches beyond advertisements. | No changes | Increase in engineering membership. Dedicated focus on public beta. | Merging of the previous `ui-and-a11y` and `analytics` Working Groups. Reduce overlap between these two groups and reduce turnaround time for critical issues. |

These Working Groups would replace/augment these existing groups:
- Ads
- Analytics
- UI and A11y
- Runtime
- Performance
- Infrastructure
- Bento

*Edit*: Updated with WG Facilitator names as part of this change.

**Comment by mrjoro** [comment]
Sending to @ampproject/tsc for approval since this is a proposed change to the Working Group structure.

@kristoferbaxter provided the details, but to more explicitly call out some of the practical changes:
- the Ads WG would be replaced by Monetization WG
- the Runtime WG would merge into the Performance WG
- UI and A11y and Analytics would merge into the Components WG

@kristoferbaxter, would the accessibility focus be the responsibility of the Components WG?

**Comment by kristoferbaxter** [comment]
The Components and Bento WGs would both be responsible for accessibility within their respective areas.

Following the completion of the Bento project, it might be prudent to introduce a standalone Accessibility Working Group.

**Comment by rudygalfi** [comment]
Is there time sensitivity? This seems like it would be a good topic for the TSC to discuss at its upcoming Oct 7 meeting.

**Comment by kristoferbaxter** [comment]
There is not time sensitivity, the October 7th meeting sounds prudent.

**Comment by ssantosms** [comment]
Good change

**Comment by rudygalfi** [comment]
I wanted to check if this can be closed out. What's the current status of this?

**Comment by kristoferbaxter** [comment]
This has been successfully completed. I'll close the issue now.
