### ISSUE TITLE
Rename the default branch of this repo from `master` to `main`

### ISSUE THREAD

**Issue by rsimha** [ampproject/meta#68]
As discussed in https://github.com/ampproject/amphtml/issues/32195

**Comment by rsimha** [comment]
@tobie @kristoferbaxter Would one of you be able to do this?

**Comment by rsimha** [comment]
I have the permissions and can do the renaming if you can confirm that you are okay with the rename. FWIW, from GitHub's [documentation](https://github.com/github/renaming#renaming-existing-branches), all links to the old branch name will continue to work and will get auto-redirected to the new branch.

**Comment by tobie** [comment]
Oh, please go ahead, then!

**Comment by rsimha** [comment]
Done. Screenshot for posterity:

![image](https://user-images.githubusercontent.com/26553114/113942385-b32c1580-97ce-11eb-96c1-c6cde0239f00.png)
