### ISSUE TITLE
Increase number of cherry pick approvers

### ISSUE THREAD

**Issue by kristoferbaxter** [ampproject/meta#70]
Right now there are only four [cherry-pick approvers](https://github.com/orgs/ampproject/teams/cherry-pick-approvers/members). I'd like to nominate two more and hear feedback.

1. @newmuis – Jon is the lead of Web Stories, and has been working within the AMP codebase for many years. He has a solid understanding of when release issues impact the Web Stories format and would be helpful for determining cherry picks across its increasing surface.
2. @rsimha – Raghu historically has primarily focused on the release and build systems, displaying a pragmatism about situations requiring or benefiting from cherry picks to production systems.

**Comment by mrjoro** [comment]
LGTM!

**Comment by jridgewell** [comment]
Now that @kristoferbaxter is leaving, I'd like to request that I also be added as a cherry-pick approver. I've a long record of investigating and fixing p0 bugs, have knowledge of runtime/bento/JS CDN/AMP Document Cache, and I'm an [owner](https://github.com/ampproject/amphtml/blob/fb7b4b5cca9d30f9b1686d51aa0b6d8775fe32ab/OWNERS#L11) of the entire AMP codebase.

**Comment by mrjoro** [comment]
Added!
