### ISSUE TITLE
Getting Registered for AMP

### ISSUE THREAD

**Issue by danchar** [ampproject/meta#71]
Hi,

I registered for AMP for a client under the email danielcharles@skie.com.au.

Any update on if I have been successful or not? As it's be 8 days (3 longer than the 5 days).

Thanks

**Comment by sebastianbenz** [comment]
@patrickkettner

**Comment by patrickkettner** [comment]
Hi @danchar!

You will want to reach out to ampforemail+registration@google.com so they can work with you to figure out what is going on with the registration. Let me know if there is anything else you need!
